actor "Skeleton" as controller
participant "r: Robot" as r
participant "a: Asteroid" as a
participant "dest: Asteroid" as dest
participant ": Game" as game


controller->r ++: move(dest)
        r->dest ++:acceptWorker(r)
            dest->r ++: setAsteroid(dest)
            return
            
            dest->dest ++: checkBaseWin()
            return false
            
		return true
        
        r->a ++:removeWorker(r)
		return
        
return

