actor "Skeleton" as player
participant "s: Settler" as s
participant  "inv: Inventory" as inv
participant "a: Asteroid" as a
participant "core: Iron" as core
participant ": Game" as g

player->s ++:mine()
    s->a ++:mined(s)
        alt layer == layersDrilled
            a->s ++: acceptMaterial(core)
		        s->s ++: isInventoryFull()
		            s-->inv ++: isFull()
		            return false
		        s-->s --:false
		        
		        s-->inv ++: addMaterial(core)
		        return
		        return true
		        
                a->a ++: removeMaterial()
                return
				a->a ++: checkBaseWin()
				return false
				
				a-->s :true
				s-->player: true
				
				
            
        else else 
            return false
            return false
        end
