participant "tvc : TeleportViewControl" as avc
participant "jb : JButton" as jb
participant " : CommandDatabase" as cmdDatBase

[->avc ++:drawAsItem(jb)
    avc-> jb++:setEnabled(true)
    return
   
    avc-> jb ++:setIcon(teleportImage)
    return
     avc->cmdDatBase ++: getTeleportID(teleport)
    return teleportID
    avc-> jb ++:setActionCommand("placeTeleport_" + teleportID)
    return
return