participant "avc : AsteroidViewControl" as avc
participant "jb : JButton" as jb
participant " : CommandDatabase" as cmdDatBase

[->avc ++:draw(jb)
    avc-> jb++:setEnabled(true)
    return
   
    avc-> jb ++:setIcon(asteroidImage)
    return
     avc->cmdDatBase ++: getAsteroidID(asteroid)
    return asteroidID
    avc-> jb ++:setActionCommand("move_" + asteroidID)
    return
    
    
return