participant "mvc : MaterialViewControl" as avc
participant "jb : JButton" as jb
participant " : CommandDatabase" as cmdDatBase

[->avc ++:draw(jb)
    avc-> jb++:setEnabled(false)
    return
   
    avc-> jb ++:setIcon(materialImage)
    return
return