participant "tvc : TeleportViewControl" as avc
participant "jb : JButton" as jb
participant " : CommandDatabase" as cmdDatBase

[->avc ++:draw(jb)
    avc-> jb++:setEnabled(true)
    return
   
    avc-> jb ++:setIcon(teleportImage)
    return
     avc->cmdDatBase ++: getTeleportID(teleport)
    return teleportID
    avc-> jb ++:setActionCommand("move_" + teleportID)
    return
return