participant "sip : SettlerInfoPanel" as sip
participant "s : Settler" as s
participant "a : Asteroid" as a
participant "inv : Inventory" as inv
participant " : ViewControlDatabase" as vcDatBase
participant "b : JButton" as b
participant "b_i : JButton" as b_i

participant "m_i : MaterialViewControl" as mv_i
participant "t_i : TeleportViewControl" as tvc_i

[->sip ++: update(s)
    sip->s ++:getAsteroid()
    return a
    sip->s ++:getInventory()
    return inv
    
    
    sip->a ++:isExposed()
    return exposed
    alt !exposed
        sip->sip ++: make drill button clickable
        return
        sip->sip ++: make mine button unclickable
        return
    else else
        sip->sip ++: make drill button unclickable
        return
        sip->sip ++: make mine button clickable
        return
    end
    
    alt inventory has enough to craft teleport
        sip->sip ++: make craft teleport button clickable
        return
    else else
        sip->sip ++: make craft teleport button unclickable
        return
    end
    
    alt inventory has enough to craft robot
        sip->sip ++: make craft robot button clickable
        return
    else else
        sip->sip ++: make craft robot button unclickable
        return
    end
    
    
    loop for JButton b in buttons representing stored material
        sip-> b ++:setEnabled(false)
        return
    end
    
    loop for JButton b in buttons representing stored teleport
        sip-> b ++:setEnabled(false)
        return
    end
    
    loop for i-th Material m_i in inventory and i-th JButton b_i representing stored material
        sip -> vcDatBase ++: getMaterialViewControl(m_i)
        return mv_i
        sip -> mv_i ++: draw(b_i)
        return
    end
    
    sip -> s ++: getTeleports()
    return teleports
    
    loop for i-th Teleport t_i in teleports and i-th JButton b_i representing stored teleport
        sip -> vcDatBase ++: getTeleportViewControl(t_i)
        return tvc_i
        sip->tvc_i ++: drawAsItem(b_i)
        return
    end
    
return