participant "a: Asteroid" as a
participant "core: Material" as core

[->a ++: step()
alt is about to be close to the sun
		a->a ++: setSunClose(true)
		deactivate a
else is about to be away from the sun
		a->a ++: setSunClose(false)
		deactivate a
end

opt is exposed && core is not null
		a->core ++: exposed()
		a<--core --
end
[<--a --
