/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tau.asteroidgame;

import tau.asteroidgame.Util.Logger;
import tau.asteroidgame.Util.UseCase;
import tau.asteroidgame.Util.usecases.*;


public class App {
    private static final UseCase[] completeUsecases = {
            new NotPlacedTeleportGetsDestroyed(),
            new PlacedTeleportGetsDestroyed(),
            new RobotDrillsToCoalCore(),
            new RobotDrillsToIceCore(),
            new RobotDrillsToUraniumCore(),
            new RobotDrillsToIronCore(),
            new RobotMovesToAsteroid(),
            new RobotMovesWithTeleportWhosePairIsNotPlaced(),
            new RobotMovesWithTeleportThatHasPlacedPair(),
            new SettlerCraftsRobotSuccessfully(),
            new SettlerCraftsTeleportSuccessfully(),
            new SettlerDrillsToCoalCore(),
            new SettlerDrillsToIceCore(),
            new SettlerDrillsToIronCore(),
            new SettlerDrillsToUraniumCore(),
            new SettlerHitBySunstorm(),
            new SettlersLose(),
            new SettlerMinesNonEmptyCoreAsteroid(),
            new SettlerMovesToAsteroid(),
            new SettlerMovesWithTeleportWhosePairIsNotPlaced(),
            new SettlerMovesWithTeleportThatHasPlacedPair(),
            new SettlerPlacesMaterialIntoEmptyCoreAsteroid(),
            new SettlerPlacesMaterialIntoNotEmptyCoreAsteroid(),
            new SettlerPlacesTeleportSuccessfully(),
            new SettlerPlacesTeleportUnsuccessfully(),
            new SettlersWin()
    };

    private static void showOptions() {
        int i;
        for (i = 0; i < completeUsecases.length; i++) {
            System.out.println("("+i+") "+ completeUsecases[i].toString());
        }
        System.out.println("("+ i +") Kilépés");
    }

    public static void main(String[] args) {

        boolean run =true;
        Logger.registerObject(Game.INSTANCE,"Game");
        while (run){
            showOptions();
            int option = Logger.getUnsignedIntInput("Melyik usecase-t szeretné futtatni?");
            if(option >= completeUsecases.length)
                run = false;
            else {
                UseCase useCase = completeUsecases[option];
                System.out.println("\n-----Kommunikációs Diagram-----\n");
                useCase.init();
                System.out.println("\n-----Szekvencia Diagram-----\n");
                useCase.run();
                System.out.println();
                System.out.println("-----DONE-----");
                Logger.clear();
            }
        }
    }
}
