
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tau.asteroidgame;

import java.awt.*;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import tau.asteroidgame.UserInterface.InputController;
import tau.asteroidgame.UserInterface.MainFrame;
import tau.asteroidgame.UserInterface.MainMenuPanel;
import tau.asteroidgame.Util.CommandLine;

import javax.swing.*;

public class App {
	public static void main(String[] args) {
		MainFrame frame = new MainFrame();
		InputController.getInstance().setMainFrame(frame);

	}
}