participant "mvc : MaterialViewControl" as avc
participant "jb : JButton" as jb
participant " : CommandDatabase" as cmdDatBase

[->avc ++:drawAsItem(jb)
    avc-> jb++:setEnabled(true)
    return
   
    avc-> jb ++:setIcon(materialImage)
    return
     avc->cmdDatBase ++: getMaterialID(material)
    return materialID
    avc-> jb ++:setActionCommand("placeItem_" + teleportID)
    return
return