participant ":Game" as game
participant "af: AsteroidField" as af
participant "ar: AsteroidRegistry" as ar
participant "a: Asteroid" as a


game->af:step()
activate af
    opt random
        af->af: induceSolarStorm()
		activate af
				af->ar **: <<create>>
                af->a ++: sufferSolarstorm(1,ar)
                return
                deactivate a
        af-->af
        deactivate af
        
    end
    
af-->game
deactivate af
