participant "a: Asteroid" as a
participant "w: Worker" as w
participant "i: Inventory"
participant "baseResReg: BaseResourceRegistry" as baseResReg

[->a ++: checkBaseWin()
    a->baseResReg **: <<create>> BaseResourceRegistry()
    
    loop for w in workers
        a->w ++: getInventory()
        return i
        a->baseResReg ++: register(i)
        return
    end
    
    a->baseResReg ++: isSuccessful
    alt have at least 3 of every material type
        baseResReg-->a: true
        a-->[: true
    else else
        baseResReg-->a --: false
        a-->[ --: false
end

