participant "s: Settler" as s
participant "t: Teleport" as t
participant "a: Asteroid" as a

[->s ++:placeTeleport()

    opt has at least 1 teleport t
        s->t++: place(a)
            t->a ++: addNeighbor(t)
            return
    
    return
    s-->[ :true
    end
    s-->[ --: false
    
        