participant "a: Asteroid" as a
participant "s: Settler" as s
participant "t: Teleport" as t
participant ":Game" as game

a->s:die()
activate s
    loop while have undestroyed Teleport t
        s->t:destroy()
        activate t
        t-->s
        destroy t
    end
    s->a ++: removeWorker(s)
    return
    
    s->game: removeSettler(s)
    activate game
        game->game ++: removeSteppable(s)
        return
        opt no more settlers left
            game->game:endGame(false)
            activate game
            game-->game
            deactivate game
        end
    game-->s
    deactivate game
s-->a
destroy s