participant "s: Settler" as s
participant "a: Asteroid" as a
participant "m: Material" as m

[->s ++: placeMaterial(m)
    s->a ++:acceptMaterial(m)
        a->a ++: isExposed()
        return exposed
        alt exposed && core is empty
            opt sunclose
                a->m ++:exposed(a)
                return
            end
            a-->s: true
            s-->[: true
        else else
        a-->s --: false
        s-->[ --: false
	end