participant ":Game" as game
participant "r: Robot" as r
participant "a: Asteroid" as a
participant "t: Transporter" as a2

game->r ++:step()
    r->a ++:isExposed()
    return isExposed
    
    r->a ++:getSunClose()
    return sunclose
    
    
    alt [!isExposed & ( (sunclose && decides the risk is worth it) || !sunclose) )
        r->a ++:drill()
        return
    else else
        r->a ++:getNeighbors()
        return neighbors
        opt neighbors not empty
            r->r ++:move(t)
            return
        end
    end
return

