participant "t: Teleport" as t
participant "s1: Settler" as s1
participant "a1: Asteroid" as a1
participant "pair: Teleport" as pair
participant "s2: Settler" as s2
participant "a2: Asteroid" as a2

[->t ++: destroy()
t->t ++:isPlaced()
return placed
alt placed
		t->a1 ++: removeNeighbor(t)
		return
else else
		t->s1 ++: removeTeleport(t)
		return
end
t->pair ++: isPlaced()
return pairPlaced
alt placed
        t->pair ++:getAsteroid()
        return a2
		t->a2 ++: removeNeighbor(pair)
		return
else else
        t->pair ++:getHolder()
        return s2
		t->s2 ++: removeTeleport(pair)
		return
end
destroy pair
'^ Ez jó? 
[<--t !!
