participant "ufo: UnidentifiedFlyingObject" as ufo
participant "inv: UFOInventory" as inv
participant "a: Asteroid" as a
participant "a2: Asteroid" as a2


[->ufo ++:step()
    ufo->a++: isExposed()
    return exposed
    alt exposed == true && UFO thinks core is not empty
        ufo->a ++:mined(inv)
        return miningSucceeded
    else else
        ufo-> a ++: getNeighbors()
        return neighbors
        
        opt neighbors is not empty
        ufo->ufo ++:move(a2)
        return
        end
    
    end
return