left to right direction

state "Core Covered" as cc
state "Core Exposed" as ce
state "Core Mined" as cm

cc: Az aszteroida köpenye még
cc: nincs teljesen kifúrva

ce: Az aszteroida köpenye teljesen
ce: ki van fúrva

cm: Az aszteroida belseje teljesen
cm: ki van bányászva

[*] --> cc

cc --> cc : drilled() [layersDrilled - 1 < layer] / layersDrilled +=1

cc --> ce : drilled() [layersDrilled - 1 >= layer] / layersDrilled = layer

ce --> ce : drilled()

ce --> cm: mined()
cm --> ce: placeMaterial()

ce --> [*] : explode()
cc --> [*]: explode()
